"use client";
import { useEffect, useState } from "react";
import { api } from "../../lib/api";
import { ExpenseBudgetChart } from "../../components/expense-budget-chart";
import { CategoryBadge } from "../../components/category";
import { MonthPicker } from "../../components/month-picker";
import { GettingStarted } from "../../components/getting-started";
import { EmptyState, ErrorState, LoadingSkeleton } from "../../components/ui";

type Category = { name: string; icon?: string | null; color?: string | null };
type Row = { categoryId: string; category: string; planned: string; actual: string; status?: string; icon?: string | null; color?: string | null };
type D = { plannedIncome: string; actualIncome: string; actualExpense: string; remainingCashFlow: string; plannedSaving: string; overspending: { category: Category; overspendingAmount: string }[]; unbudgetedExpenses: { category: Category; actualAmount: string }[]; recentTransactions: { id: string; transactionDate: string; amount: string; type: string; category: Category }[]; chart: Row[]; walletBalances: { id: string; name: string; balance: string }[] };
const money = (v: string) => { const [n, d] = v.split("."); return n.replace(/\B(?=(\d{3})+(?!\d))/g, ".") + (d && d !== "00" ? "," + d : "") + "đ"; };
const sumMoney = (values: string[]) => { const cents = values.reduce((t, value) => { const [whole, fraction = ""] = value.replace(/^-/, "").split("."); const amount = BigInt(whole || "0") * 100n + BigInt((fraction + "00").slice(0, 2)); return t + (value.startsWith("-") ? -amount : amount); }, 0n); const absolute = cents < 0n ? -cents : cents; return `${cents < 0n ? "-" : ""}${absolute / 100n}.${(absolute % 100n).toString().padStart(2, "0")}`; };
const percent = (actual: string, planned: string) => { const toCents = (v: string) => { const [w, f = ""] = v.replace(/^-/, "").split("."); return BigInt(w || "0") * 100n + BigInt((f + "00").slice(0, 2)); }; const p = toCents(planned); return p === 0n ? 0 : Number((toCents(actual) * 10000n) / p) / 100; };

export default function Dashboard() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)), [data, setData] = useState<D | null>(null), [categories, setCategories] = useState<Category[]>([]), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); Promise.all([api<D>(`/dashboard?month=${month}`), api<{ items: Category[] }>("/categories")]).then(([d, c]) => { setData(d); setCategories(c.items); }).catch(() => setError("Không thể tải dashboard.")).finally(() => setLoading(false)); };
  useEffect(load, [month]);
  if (loading) return <main><LoadingSkeleton label="Đang tải dashboard…" /></main>;
  if (error || !data) return <main><ErrorState message={error || "Không có dữ liệu."} onRetry={load} /></main>;
  const categoryFor = (name: string, icon?: string | null, color?: string | null) => ({ name, icon: icon ?? categories.find((c) => c.name === name)?.icon, color: color ?? categories.find((c) => c.name === name)?.color });
  return <main>
    <div className="planner-welcome"><div><h1>Xin chào! <span aria-hidden="true">👋</span></h1><p className="muted">Cùng nhìn lại kế hoạch tháng này nhé.</p></div><label className="planner-month">Tháng<MonthPicker value={month} onChange={setMonth} /></label></div>
    <GettingStarted month={month} hasWallet={data.walletBalances.length > 0} hasPlan={data.chart.length > 0} hasTransactions={data.recentTransactions.length > 0} />
    <section className="planner-budget-card card"><div><p className="eyebrow">TỔNG TÀI SẢN</p><strong>{money(sumMoney(data.walletBalances.map((x) => x.balance)))}</strong><div className="planner-metrics"><span>Thu nhập tháng<strong>{money(data.actualIncome)}</strong></span><span>Đã chi<strong>{money(data.actualExpense)}</strong></span><span>Dòng tiền ròng<strong>{money(data.remainingCashFlow)}</strong></span></div></div><div className="planner-progress"><span style={{ width: `${Math.min(100, percent(data.actualExpense, data.plannedIncome))}%` }} /></div><small>Chi tiêu so với thu nhập tháng</small></section>
    <section className="card wallet-overview"><div className="section-heading"><div><h2>Ví tiền</h2><p className="muted">Số dư hiện tại ở từng nơi</p></div><a href="/wallets">Quản lý ví</a></div><div className="wallet-overview-grid">{data.walletBalances.map((x) => <div key={x.id}><span>{x.name}</span><strong>{money(x.balance)}</strong></div>)}</div></section>
    <div className="planner-grid"><section className="card planner-categories"><div className="section-heading"><div><h2>Danh mục</h2><p className="muted">Theo dõi tiến độ từng khoản</p></div><a href="/categories">Xem tất cả</a></div>{data.chart.length === 0 ? <EmptyState title="Chưa có kế hoạch" description="Tạo kế hoạch tháng để bắt đầu." action={<a href={`/plans/${month.split("-")[0]}/${month.split("-")[1]}`}>Tạo kế hoạch</a>} /> : data.chart.map((x) => <div className="planner-category" key={x.categoryId}><CategoryBadge category={categoryFor(x.category, x.icon, x.color)} compact /><div><small>{money(x.actual)} / {money(x.planned)}</small><div className="category-progress"><i style={{ width: `${Math.min(100, percent(x.actual, x.planned))}%` }} /></div></div><b>{x.planned === "0.00" ? "—" : `${Math.round(percent(x.actual, x.planned))}%`}</b></div>)}</section><section className="card planner-recent"><div className="section-heading"><div><h2>Giao dịch gần đây</h2><p className="muted">Những khoản mới nhất</p></div><a href="/transactions">Xem tất cả</a></div>{data.recentTransactions.length === 0 ? <EmptyState title="Chưa có giao dịch" description="Ghi nhận khoản thu hoặc chi đầu tiên." action={<a href="/transactions">Thêm giao dịch</a>} /> : data.recentTransactions.slice(0, 6).map((x) => <div className="planner-transaction" key={x.id}><CategoryBadge category={x.category} compact /><small>{x.transactionDate}</small><b className={x.type === "INCOME" ? "income" : "expense"}>{x.type === "INCOME" ? "+" : "-"}{money(x.amount)}</b></div>)}</section></div>
    <div className="planner-actions"><a href="/transactions?type=EXPENSE">＋ Thêm khoản chi</a><a href={`/plans/${month.split("-")[0]}/${month.split("-")[1]}`}>＋ Mở kế hoạch tháng</a></div>
    <section className="planner-chart"><ExpenseBudgetChart data={data.chart} /></section>
    <div className="planner-alerts"><section className="card"><h2>Vượt ngân sách</h2>{data.overspending.length === 0 ? <p className="muted">Chưa có danh mục vượt ngân sách.</p> : data.overspending.map((x) => <p key={x.category.name}><CategoryBadge category={x.category} compact /> · vượt {money(x.overspendingAmount)}</p>)}</section><section className="card"><h2>Chi chưa lập ngân sách</h2>{data.unbudgetedExpenses.length === 0 ? <p className="muted">Tất cả khoản chi đã có ngân sách.</p> : data.unbudgetedExpenses.map((x) => <p key={x.category.name}><CategoryBadge category={x.category} compact /> · {money(x.actualAmount)}</p>)}</section></div>
  </main>;
}
