import assert from 'node:assert/strict';
import {PrismaService} from '../../apps/api/src/prisma.service.js';
import {TransactionsService} from '../../apps/api/src/transactions.service.js';
import {TransactionCreateDto} from '../../apps/api/src/transactions.dto.js';
import {WalletsService} from '../../apps/api/src/wallets.service.js';

const db=new PrismaService(); const service=new TransactionsService(db); const wallets=new WalletsService(db);
const dto=(type:'INCOME'|'EXPENSE',walletId:string,categoryId:string,amount:string,date:string):TransactionCreateDto=>({type,walletId,categoryId,amount,transactionDate:date});
async function main(){await db.$connect();const suffix=Date.now().toString();const [a,b]=await Promise.all([db.user.create({data:{email:`a-${suffix}@test.local`,passwordHash:'x'}}),db.user.create({data:{email:`b-${suffix}@test.local`,passwordHash:'x'}})]);const aw=await db.wallet.create({data:{userId:a.id,name:'A wallet',type:'cash',initialBalance:'5000000'}});const bw=await db.wallet.create({data:{userId:b.id,name:'B wallet',type:'cash',initialBalance:'0'}});const ai=await db.category.create({data:{userId:a.id,name:'Salary',type:'INCOME'}});const ae=await db.category.create({data:{userId:a.id,name:'Food',type:'EXPENSE'}});const be=await db.category.create({data:{userId:b.id,name:'Food',type:'EXPENSE'}});
const income=await service.create(a.id,dto('INCOME',aw.id,ai.id,'2000000','2026-08-01'));const expense=await service.create(a.id,dto('EXPENSE',aw.id,ae.id,'1000000','2026-08-31'));assert.equal(income.amount,'2000000.00');assert.equal(expense.amount,'1000000.00');await assert.rejects(()=>service.create(a.id,dto('INCOME',aw.id,ae.id,'1','2026-08-01')));await assert.rejects(()=>service.create(a.id,dto('EXPENSE',bw.id,be.id,'1','2026-08-01')));await assert.rejects(()=>service.create(a.id,dto('EXPENSE',aw.id,ae.id,'0','2026-08-01')));await db.wallet.update({where:{id:aw.id},data:{archivedAt:new Date()}});await assert.rejects(()=>service.create(a.id,dto('EXPENSE',aw.id,ae.id,'1','2026-08-01')));await db.wallet.update({where:{id:aw.id},data:{archivedAt:null}});await db.category.update({where:{id:ae.id},data:{archivedAt:new Date()}});await assert.rejects(()=>service.create(a.id,dto('EXPENSE',aw.id,ae.id,'1','2026-08-01')));await db.category.update({where:{id:ae.id},data:{archivedAt:null}});await assert.rejects(()=>service.get(b.id,income.id));await assert.rejects(()=>service.update(b.id,income.id,{amount:'3'}));await assert.rejects(()=>service.remove(b.id,income.id));
const listed=await service.list(a.id,{month:'2026-08',page:'1',pageSize:'1'});assert.equal(listed.total,2);assert.equal(listed.items.length,1);assert.equal(listed.pageSize,1);assert.equal((await wallets.list(a.id))[0].currentBalance,'6000000.00');const moved=await service.update(a.id,expense.id,{amount:'7000000',transactionDate:'2026-09-01',walletId:aw.id,categoryId:ae.id,type:'EXPENSE',note:'updated'});assert.equal(moved.amount,'7000000.00');assert.equal((await service.list(a.id,{month:'2026-08'})).total,1);assert.equal((await service.list(a.id,{month:'2026-09'})).total,1);await service.remove(a.id,income.id);assert.equal((await service.list(a.id,{})).total,1);assert.equal((await wallets.list(a.id))[0].currentBalance,'-2000000.00');await assert.rejects(()=>service.get(a.id,income.id));
await db.transaction.deleteMany({where:{userId:{in:[a.id,b.id]}}});await db.wallet.deleteMany({where:{userId:{in:[a.id,b.id]}}});await db.category.deleteMany({where:{userId:{in:[a.id,b.id]}}});await db.user.deleteMany({where:{id:{in:[a.id,b.id]}}});await db.$disconnect();console.log('integration transactions: PASS');}
main().catch(async e=>{console.error(e);await db.$disconnect();process.exitCode=1;});
