"use client";
import { useEffect, useState } from "react";
import { api } from "../../lib/api";
import { CategoryBadge } from "../../components/category";
import { MonthPicker } from "../../components/month-picker";
import { ErrorState, EmptyState, LoadingSkeleton, PageHeader, StatCard } from "../../components/ui";
import { currentMonth } from "../../lib/movements";
type Category = { name: string; type?: "INCOME" | "EXPENSE"; icon?: string | null; color?: string | null };
type R = { month: string; previousMonth: string; currentExpense: string; previousExpense: string; difference: string; differencePercentage: number | null; comparisonStatus: string; byCategory: { category: string; currentExpense: string; previousExpense: string; isNew: boolean; isNoLongerUsed: boolean }[] };
const money = (v: string) => { const [n, d] = v.split("."); return `${n.replace(/\B(?=(\d{3})+(?!\d))/g, ".")}${d && d !== "00" ? "," + d : ""}đ`; };
const monthLabel = (value: string) => { const [year, month] = value.split("-"); return `${month}/${year}`; };
export default function Analysis() {
  const [month, setMonth] = useState(currentMonth), [data, setData] = useState<R | null>(null), [categories, setCategories] = useState<Category[]>([]), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); setError(""); Promise.all([api<R>(`/reports/monthly-comparison?month=${month}`), api<{ items: Category[] }>("/categories")]).then(([r, c]) => { setData(r); setCategories(c.items); }).catch(() => setError("Không thể tải phân tích tháng này.")).finally(() => setLoading(false)); };
  useEffect(load, [month]);
  if (loading) return <main><LoadingSkeleton label="Đang đọc lại dòng tiền…" /></main>;
  return <main><PageHeader title="Phân tích tháng" description="So sánh dòng tiền thực tế với tháng trước để bạn biết điều gì đang thay đổi." actions={<label>Tháng <MonthPicker value={month} onChange={setMonth} /></label>} />{error ? <ErrorState message={error} onRetry={load} /> : data && <><section className="stat-grid analysis-summary"><StatCard label="Chi tháng này" value={money(data.currentExpense)} tone="danger" /><StatCard label="Chi tháng trước" value={money(data.previousExpense)} /><StatCard label="Chênh lệch" value={money(data.difference)} tone={data.difference.startsWith("-") ? "success" : "warning"} /><StatCard label="So với tháng trước" value={data.differencePercentage === null ? data.comparisonStatus === "NEW_SPENDING" ? "Mới phát sinh" : "Chưa có chi" : `${data.differencePercentage}%`} /></section><section className="card analysis-table-card"><div className="section-heading"><div><h2>Chi tiêu theo danh mục</h2><p className="muted">Đối chiếu {monthLabel(data.month)} với {monthLabel(data.previousMonth)}.</p></div></div>{data.byCategory.length === 0 ? <EmptyState title="Chưa có dữ liệu so sánh" description="Ghi nhận giao dịch để bắt đầu nhìn thấy xu hướng." /> : <div className="analysis-table-wrap"><table><thead><tr><th>Danh mục</th><th>Tháng này</th><th>Tháng trước</th><th>Trạng thái</th></tr></thead><tbody>{data.byCategory.map((x) => { const c = categories.find((item) => item.name === x.category); return <tr key={x.category}><td><CategoryBadge category={c ?? { name: x.category, type: "EXPENSE" }} compact /></td><td>{money(x.currentExpense)}</td><td>{money(x.previousExpense)}</td><td>{x.isNew ? <span className="badge badge-warning">Mới phát sinh</span> : x.isNoLongerUsed ? <span className="badge">Không còn phát sinh</span> : <span className="badge badge-success">Ổn định</span>}</td></tr>; })}</tbody></table></div>}</section></>}</main>;
}
