import {BadRequestException,Inject,Injectable,NotFoundException} from '@nestjs/common';
import {Prisma,TransactionType} from '@prisma/client';
import {PrismaService} from './prisma.service.js';
import {AllocationsDto,PlanDto} from './monthly-plans.dto.js';
import {allocationResult} from '../../../packages/shared/src/finance.js';

const money=(s:string)=>{const d=new Prisma.Decimal(s);if(d.isNegative()||d.decimalPlaces()>2||d.precision(true)>19)throw new BadRequestException('INVALID_AMOUNT');return d;};
const cents=(d:Prisma.Decimal)=>BigInt(d.mul(100).toFixed(0));
const period=(y:number,m:number)=>{if(!Number.isInteger(y)||y<1||!Number.isInteger(m)||m<1||m>12)throw new BadRequestException('INVALID_DATE');return{from:new Date(Date.UTC(y,m-1,1)),to:new Date(Date.UTC(y,m,1))};};
const text=(d:Prisma.Decimal)=>d.toFixed(2);

@Injectable()
export class MonthlyPlansService { constructor(@Inject(PrismaService)private readonly db:PrismaService){}
  async get(uid:string,y:number,m:number){const {from,to}=period(y,m);const plan=await this.db.monthlyPlan.findUnique({where:{userId_year_month:{userId:uid,year:y,month:m}}});if(!plan)throw new NotFoundException('NOT_FOUND');const tx=await this.db.transaction.findMany({where:{userId:uid,deletedAt:null,transactionDate:{gte:from,lt:to}},select:{type:true,amount:true,categoryId:true}});const income=tx.filter(x=>x.type===TransactionType.INCOME).reduce((s,x)=>s.plus(x.amount),new Prisma.Decimal(0));const expense=tx.filter(x=>x.type===TransactionType.EXPENSE).reduce((s,x)=>s.plus(x.amount),new Prisma.Decimal(0));const allocations=await this.db.monthlyBudgetAllocation.findMany({where:{monthlyPlanId:plan.id},include:{category:{select:{id:true,name:true,type:true}}}});const cats=await this.db.category.findMany({where:{userId:uid,type:'EXPENSE',archivedAt:null},select:{id:true,name:true,type:true}});const actual=new Map<string,Prisma.Decimal>();for(const x of tx.filter(x=>x.type===TransactionType.EXPENSE))actual.set(x.categoryId,(actual.get(x.categoryId)??new Prisma.Decimal(0)).plus(x.amount));const ids=new Set(allocations.map(x=>x.categoryId));const budgets=[...allocations.map(x=>({category:x.category,plannedAmount:x.plannedAmount})),...cats.filter(x=>!ids.has(x.id)&&actual.has(x.id)).map(category=>({category,plannedAmount:new Prisma.Decimal(0)}))].map(x=>{const a=actual.get(x.category.id)??new Prisma.Decimal(0);const r=allocationResult(cents(x.plannedAmount),cents(a));return{category:x.category,plannedAmount:text(x.plannedAmount),actualAmount:text(a),remainingBudget:text(x.plannedAmount.minus(a)),usagePercentage:r.usagePercentage,overspendingAmount:text(x.plannedAmount.lt(a)?a.minus(x.plannedAmount):new Prisma.Decimal(0)),status:r.status};});const total=allocations.reduce((s,x)=>s.plus(x.plannedAmount),new Prisma.Decimal(0));const available=plan.plannedIncome.plus(plan.carryOver);return{...plan,plannedIncome:text(plan.plannedIncome),carryOver:text(plan.carryOver),plannedSaving:text(plan.plannedSaving),plannedAvailableMoney:text(available),totalExpenseAllocated:text(total),totalAllocated:text(total.plus(plan.plannedSaving)),unallocatedAmount:text(available.minus(total).minus(plan.plannedSaving)),actualIncome:text(income),actualExpense:text(expense),remainingCashFlow:text(income.plus(plan.carryOver).minus(expense)),budgets};}
  async put(uid:string,y:number,m:number,b:PlanDto){period(y,m);const plan=await this.db.monthlyPlan.upsert({where:{userId_year_month:{userId:uid,year:y,month:m}},create:{userId:uid,year:y,month:m,plannedIncome:money(b.plannedIncome),carryOver:money(b.carryOver),plannedSaving:money(b.plannedSaving??'0')},update:{plannedIncome:money(b.plannedIncome),carryOver:money(b.carryOver),plannedSaving:money(b.plannedSaving??'0')}});return this.get(uid,plan.year,plan.month);}
  async allocations(uid:string,y:number,m:number,b:AllocationsDto){period(y,m);const plan=await this.db.monthlyPlan.findUnique({where:{userId_year_month:{userId:uid,year:y,month:m}}});if(!plan)throw new NotFoundException('NOT_FOUND');const vals=b.allocations.map(x=>({categoryId:x.categoryId,plannedAmount:money(x.plannedAmount)}));if(new Set(vals.map(x=>x.categoryId)).size!==vals.length)throw new BadRequestException('VALIDATION_ERROR');const cats=await this.db.category.findMany({where:{id:{in:vals.map(x=>x.categoryId)},userId:uid,type:'EXPENSE',archivedAt:null}});if(cats.length!==vals.length)throw new NotFoundException('NOT_FOUND');const total=vals.reduce((s,x)=>s.plus(x.plannedAmount),new Prisma.Decimal(0)).plus(plan.plannedSaving);if(total.gt(plan.plannedIncome.plus(plan.carryOver)))throw new BadRequestException('ALLOCATION_EXCEEDS_AVAILABLE');await this.db.$transaction(async tx=>{await tx.monthlyBudgetAllocation.deleteMany({where:{monthlyPlanId:plan.id}});if(vals.length)await tx.monthlyBudgetAllocation.createMany({data:vals.map(x=>({...x,monthlyPlanId:plan.id}))});});return this.get(uid,y,m);}
}
